meta-data:
  repository_name: yamlcli
  visibility: public
  org-name: RyoNakagami
  tag:
    - cli-tool
    - command-line
    - uv
    - uvx
    - yaml
    - json
    - python
  description: |
    A command-line tool to convert between YAML and JSON formats.
  license: mit
